### ISSUE TITLE
Refactor the code

### ISSUE THREAD

**Issue by ranafaraz** [ranafaraz/college_management_system#1]
Refactor the code  using PHP require method. Break code chunks into multiple files.

**Comment by ranafaraz** [comment]
Mr. @AnasShafqat kindly comment briefly what you have achieved regarding this issue. 
Thanks

**Comment by ranafaraz** [comment]
Relevant developers are directed to fork the project and generate pull request.

**Comment by naumanshahid007** [comment]
Re-factorization has been done.
